CREATE TABLE Comment(
    ID_Comment INTEGER PRIMARY KEY AUTOINCREMENT,
    Content TEXT NOT NULL,
    Images TEXT NOT NULL,
    ID_User INTEGER NOT NULL,
    ID_Post INTEGER NOT NULL,
    ID_Group INTEGER NOT NULL,
    Types   TEXT NOT NULL,
    FOREIGN KEY (ID_User) REFERENCES User(ID_User),
    FOREIGN KEY (ID_Post) REFERENCES User(ID_Post)
);