CREATE TABLE Follow(
    ID_Follow INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_User INTEGER NOT NULL,
    Receiver TEXT NOT NULL,
    Privacy TEXT NOT NULL,
    Operation TEXT NOT NULL,
    Types TEXT NOT NULL,
    ID_Group INTEGER NOT NULL,
    FOREIGN KEY (ID_User) REFERENCES User(ID_User),
    FOREIGN KEY (ID_Group) REFERENCES Groupe(ID_Group)
);