CREATE TABLE Chat(
    ID_Chat INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_User INTEGER NOT NULL,
    ID_Receiver INTEGER NOT NULL,
    Content TEXT NOT NULL,
    Types TEXT NOT NULL,
    ID_Group INTEGER NOT NULL,
    FOREIGN KEY (ID_User) REFERENCES User(ID_User),
    FOREIGN KEY (ID_Group) REFERENCES Groupe(ID_Group)
);